USE [master]
GO


/****** Object:  Database [Hospital]    Script Date: 12/31/2018 12:49:03 AM ******/
CREATE DATABASE [Hospital]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'hosptial', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\hosptial.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'hosptial_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\hosptial_log.ldf' , SIZE = 2624KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Hospital] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Hospital].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Hospital] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Hospital] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Hospital] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Hospital] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Hospital] SET ARITHABORT OFF 
GO

ALTER DATABASE [Hospital] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Hospital] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Hospital] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Hospital] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Hospital] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Hospital] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Hospital] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Hospital] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Hospital] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Hospital] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Hospital] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Hospital] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Hospital] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Hospital] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Hospital] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Hospital] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Hospital] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Hospital] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Hospital] SET RECOVERY FULL 
GO

ALTER DATABASE [Hospital] SET  MULTI_USER 
GO

ALTER DATABASE [Hospital] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Hospital] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Hospital] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Hospital] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Hospital] SET  READ_WRITE 
GO









USE [Hospital]
GO

/****** Object:  Table [dbo].[Doctors]    Script Date: 12/31/2018 12:51:53 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Doctors](
	[Id] [int] NOT NULL,
	[Name] [varchar](20) NOT NULL,
 CONSTRAINT [PK__doctor__D877D2161920CDFC] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO




USE [Hospital]
GO

/****** Object:  Table [dbo].[Nurses]    Script Date: 12/31/2018 12:53:42 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Nurses](
	[Id] [int] NOT NULL,
	[Name] [varchar](20) NOT NULL,
 CONSTRAINT [PK__nurse__DF97D0F5FA791A41] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO




USE [Hospital]
GO

/****** Object:  Table [dbo].[Rooms]    Script Date: 12/31/2018 12:54:05 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Rooms](
	[Id] [int] NOT NULL,
	[Type] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO




USE [Hospital]
GO

/****** Object:  Table [dbo].[Patients]    Script Date: 12/31/2018 12:52:34 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Patients](
	[Id] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Mobile] [varchar](20) NOT NULL,
	[Address] [varchar](max) NOT NULL,
	[Gender] [varchar](10) NOT NULL,
	[Disease] [varchar](50) NOT NULL,
	[Admitted] [bit] NOT NULL,
	[DateAdmitted] [datetime] NULL,
	[DateDischarged] [datetime] NULL,
	[Bill] [int] NULL,
	[DoctorId] [int] NULL,
	[NurseId] [int] NULL,
	[RoomId] [int] NULL,
 CONSTRAINT [PK__patient__DD37D91AB10E3F03] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Patients]  WITH CHECK ADD  CONSTRAINT [FK__Patients__Doctor__07C12930] FOREIGN KEY([DoctorId])
REFERENCES [dbo].[Doctors] ([Id])
GO

ALTER TABLE [dbo].[Patients] CHECK CONSTRAINT [FK__Patients__Doctor__07C12930]
GO

ALTER TABLE [dbo].[Patients]  WITH CHECK ADD  CONSTRAINT [FK__Patients__NurseI__08B54D69] FOREIGN KEY([NurseId])
REFERENCES [dbo].[Nurses] ([Id])
GO

ALTER TABLE [dbo].[Patients] CHECK CONSTRAINT [FK__Patients__NurseI__08B54D69]
GO

ALTER TABLE [dbo].[Patients]  WITH CHECK ADD  CONSTRAINT [FK__Patients__RoomId__09A971A2] FOREIGN KEY([RoomId])
REFERENCES [dbo].[Rooms] ([Id])
GO

ALTER TABLE [dbo].[Patients] CHECK CONSTRAINT [FK__Patients__RoomId__09A971A2]
GO





USE [Hospital]
GO

/****** Object:  Table [dbo].[Users]    Script Date: 12/31/2018 12:54:19 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Users](
	[UserId] [int] NOT NULL,
	[Username] [varchar](20) NOT NULL,
	[Password] [varchar](16) NOT NULL,
	[Role] [varchar](20) NOT NULL,
	[PrivateId] [int] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO



